### ISSUE TITLE
Plugin functions executed after inline redirection

### ISSUE THREAD

**Issue by karovski** [silentrob/superscript#170]
If a reply contains a plugin function call and an inline redirect, the redirection is done first and the plugin function is called afterwards. This results in an incorrect message context (scope) for the plugin function.

For example:
```
  + test plugin redirection
  - ^doSomething() okay {@second}
  + second
  - done
```
The `doSomething` function is called for the message `second`, or bluntly the following plugin function:
```
exports.doSomething = function(cb) {
  console.log('this.message.raw', this.message.raw);
  cb(null, '');
}
```
will log:
```
this.message.raw second
```

**Comment by mariusursache** [comment]
Can u change the order in SS processing? Ask Rob if this messes up any 
logic.

**Comment by silentrob** [comment]
This is happening because the reply string is not being parsed from left to right, we process the redirect before the custom function, and due to the nature of how the redirect works, it consumes or overrides the origional input. 

ProcessTags will need to be refactored and that change is not going to be simple or quick.

**Comment by mariusursache** [comment]
Question: if we use instead of the literal redirect {@__trigger__} a ^topicRedirect(topicname,__trigger__), would it be the same problem?

**Comment by silentrob** [comment]
This should be good now (v0.10.0)
