### ISSUE TITLE
Wildcard capture oddities.

### ISSUE THREAD

**Issue by Lewwwk** [silentrob/superscript#212]
When capturing wildcards at the beginning or end of an input, I've noticed some inconsistent behaviour.

```
+ *(1-5) test
> input: this too test => expected: this too => captured: this too (AS EXPECTED)
> input: what you want test => expected: what you want => captured: what be you want (UNEXPECTED)
>>> the word you gets replace with 'be you' (this only happens when it's captured at the BEGINNING of an input)

+ test *(1-5)
> input: test this too => expected: this too => captured: this (UNEXPECTED)
> input: test what you want => expected: what you want => captured: what you want (AS EXPECTED)
>>> the word 'too' gets dropped (this only happens when it's captured at the END of an input)
```

**Comment by silentrob** [comment]
Okay, so the good news is the capture system is working as expected. In both cases you are getting hit by text normalization rules.
"what you" is becoming "what are you" and then being changed to the root form "be"
And we strip "too" off the end of the sentences because it adds no extra value to the input (just noise)
https://github.com/silentrob/normalizer/blob/master/data/substitutes.txt#L1459

**Comment by Lewwwk** [comment]
Right - makes sense.  Thx @silentrob. 

Also leaving this here for future reference: weird behaviour can easily be investigated by running the DEBUG util: `DEBUG=* node index.js`
