### ISSUE TITLE
--watch topics and reload

### ISSUE THREAD

**Issue by silentrob** [silentrob/superscript#25]
It would be nice to have the engine auto reload when the topics change.

A grunt or gulp would be ideal for this task.

**Comment by dcsan** [comment]
this is probably my biggest blocker for working with the system. 

the iteration loop is extremely long.

as it is now I have to ctrl-C, restart(parse && run) the server
then switch to another window where the telnet client quit, restart that... etc.
as opposed to just hitting "save" and seeing instant refresh.

maybe i could do TDD stuff but its much easier to see the flow of the story and iteratively write it, rather than writing a ton and then switching to play... etc.

do you have a better workflow? i'll try to setup a server client that will auto-reconnect, at least that will save one step...

**Comment by dcsan** [comment]
does the slack client keep a connection open, or reconnect if you close?

**Comment by silentrob** [comment]
The topic state is now saved in mongo, and reloading is instant.
