### ISSUE TITLE
metadata proposal

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#57]
rel #42 

> ^addMessageProp(key,value)

I intend to make a lot of use of metadata, and I think this syntax will get very verbose.
what about adding a { } block to commands on a newline?

for simple props on that message just set:

```
+ hello
- how are you?
{ topic: greeting, mood: happy }

+ punch
- ouch!
{ mood: angry }

```

for saving state, add as a 
```
{ bot.mood: angry }
```

that would allow a new line that is always run. it's a bit easier than the inline code you proposed.

**Comment by silentrob** [comment]
So you can already save state using createFact or writing directly to the level DB. Because you can pass in the LevelDB credentials you can have another connection open to it and use that elsewhere within your app. (Same goes for the user docs in mongo)

addMessageProp was designed to pass back extra data with the current reply. If you want to set multiple keys/values at once that should be trivial now.

Create a new plugin (or copy the existing addMessageProp)

    exports.addMessageProps = function(data,cb) {
      var propData = eval(data);
      for (var key,val in propData) {
        this.message.props[key] = val;
      }
      cb(null, "");
    }

That is not tested, but should give you a clear path to a win.

Then 

    - some reply ^addMessageProps({ topic: greeting, mood: happy })

should work.

What is missing here is the ability to set the data on the trigger side. Perhaps that could be a new feature. Also be extra careful not to pass user input into the function as we are evaling it.

**Comment by dcsan** [comment]
ok i'll try it out. but for non techy authors even if we abbreviated it:

    ^props({  )}

on every line of content is a lot of line noise. I'm aiming to get writer types to make these bots, not devs.

also where are the props available to the bot reply? I think i tried looking through the memory part before.

    var receiveData = function(slack, bot, data) {

would it be bot.X or data.X (data is the reply from the bot, not the user input)

**Comment by silentrob** [comment]
The propertied are merged into the reply object.

https://github.com/silentrob/superscript/blob/master/test/script.js#L520
