### ISSUE TITLE
Superscript and online ordering and quotations

### ISSUE THREAD

**Issue by airport-transfers** [silentrob/superscript#73]
Example:
HUMAN: Hi robot! Which is the price for 3 kg of apples, 5 kg of oranges, 1kg of mushrooms and 2kg of bread?
ROBOT: The total price for "3 kg of apples, 5 kg of oranges, 1kg of mushrooms and 2kg of bread" is 10 American Dollars. Do you want to add them in the cart? If you reach the 12 $ then you will have free shipment.
HUMAN: Great! Yes, thanks please add also 5 kg of banana so the price will fly over the 12 dollars. and please add them to the cart. And what about the time for the shipment?
ROBOT:  The standard shipment need a week, the express cost 5 dollars more and it arrive in 3 days. 
HUMAN: I love you robot, thanks! Please add all the products in the cart and ship them to me with standard shipment, have a great day!
ROBOT: Have a great day you too Mr Human. It was wonderful to speak with you. I am always at your service, especially if you will need more informations about our food store.

**Comment by silentrob** [comment]
Awesome. Are you asking if this is possible? You can quote a reply by capturing data back. 

    + what is the price of (*)
    - The total price for "<cap1>" is ...

Parsing out and adding up everything is slightly more challenging, but also doable. I would recommend taking a look at plugins for that part of the problem.

**Comment by airport-transfers** [comment]
Ok, so I will check the plugin here
https://github.com/silentrob/superscript/tree/master/plugins

And hat about the ordering steps?
It should be better to create forced ordering steps or a more ELASTIC STRUCTURE, more human friendly, where for example if you say the date and not the number of passengers then he ask you the missing data.
Instead the FORCED ORDERING STEPS could have for example a shape like this: STEP1: number of passengers STEP2 date of the booking STEP3 optional date to return STEP4 optionals STEP 5 buy it or not? etcetera..

**Comment by silentrob** [comment]
Just to be clear. I have't created a plugin to handle your specific use case. Rather, the approach you could take to solve this would be with a plugin to analyze the message and pull out and parse the right pieces.

For ordering, this could happen just like normal conversation flow.

See here if you are using the script/compile method
http://superscriptjs.com/documentation/scripting#convo
And another example here. 
https://github.com/silentrob/superscript/blob/master/test/fixtures/continue/main.ss
Just note Ive mixed up the +,%,- in the test and the docs are right, the order is %,+,-

If you are using the web editor this process is much easier, although plugin authoring is a little more challenging. If you need more guidance just let me know. Im here to help.

**Comment by airport-transfers** [comment]
Thanks for the answer, but to me the conversations are not yet clear, tomorrow I try to install superscript and I will try to make some tests to understand them, or maybe some more realistic examples can help me better.

**Comment by silentrob** [comment]
If the input above is what your looking to build, perhaps I can build out a tutorial to show how this is done.  Maybe it would be valuable to others as well.

**Comment by airport-transfers** [comment]
yeah! thanks!

**Comment by dcsan** [comment]
a tutorial for a concrete use-case like this would be interesting. i've been working with this stuff for a few months, and it's still hard to know how to actually apply it.

parsing with regex is one thing, but the deeper power of the other language breakdown tools (NLP?) that SS provides is really the point of using it. what comes out the other end of those is often perplexing in terms of knowing how to apply them. where would you use a lemmatization or what other tools are in the SS arsenal to break down a conversation like above into something a script can react to?

**Comment by silentrob** [comment]
So lemmatization in superscript is really just a further way to normalize the input and make matching easier or more natural. It is designed to removed any plural inflections or tense.

"I went to the store and it was closed" becomes
"I go to the store and it be close" 

Because we do this on both side (message input and triggers) we match all the variations and permutations of the verbs and nouns. 

Having said that, SuperScript does have a ton of power that could be better documented and tutorials written. Specifically around knowledge, generating facts and plugins / filters.

**Comment by silentrob** [comment]
Okay, here is a partial solution you can play with.

    + ~emohello [*~2]
    - Hi!
    - Hello

    ?:WH * is the (price|cost) (for|of) (*)
    - The total <cap1> <cap2> "<cap3>" is ^calcPrice(<cap3>). {@_add_to_cart} {@_free_shipping}

    + * ~yes *
    % *
    - Okay, I've added those items to your cart. ^addPendingToCart()

    // more direct add to cart (out of conversation flow)
    + * add to cart *
    - Okay, I've added those items to your cart. ^addPendingToCart()

    + _add_to_cart
    - Do you want to add them in the cart? 

    + _free_shipping
    - If you reach the 12 $ then you will have free shipment.

    ? * time * shipment
    - The standard shipment need a week, the express cost 5 dollars more and it arrive in 3 days.

    + * have a great day
    - Have a great day you too Mr Human. 
    ^ It was wonderful to speak with you. 
    ^ I am always at your service, especially if you will need more informations about our food store.

    + review * 
    - ^listCart()

And the Plugins

    exports.calcPrice = function(things, next) {
      var re = /(\d kilogram of [a-z]{1,}|\d pound of [a-z]{1,})/g;

      var matches = things.match(re);
      this.user.slot1 = [];
      this.user.slot1 = matches;
      this.user.save(function() {
        // TODO calculate price
        next(null, "10 American Dollars");
      });
    };

    exports.addPendingToCart = function(next) {
      // TODO merge data more gracefully
      this.user.slot2 = this.user.slot1;
      this.user.save(function(err, res) {
        next(null,"");
      });
    };

    exports.listCart = function(next) {
      next(null,this.user.slot2.join(","));
    };


This should get you going while still leaving some fun bits left to figure out.

**Comment by dcsan** [comment]
can you explain what these different items mean?

    ?:WH * is the

is a wh-type question

    + * ~yes *

some form of a yes/affirmation

    ? * time * shipment

this means (any?) type of question, with the exact keyword time?
is there a ~time for lemmatization of all time words?

is there a ?TIME type thing for when/soon/ type time related questions?

**Comment by silentrob** [comment]
I think you have the hang of it.

`?` is any question.
`?:WH` further filters the question down to just WH-Questions. (who, what, where, when and why)

Of course, you can add words and wildcards to get more specific in what you want to match, so 

    ? * time * shipment

Says, we are looking for a question with the word time and shipment in that order.
This will match.

    what about the time for the shipment?

But wont match

    I want to know more about the time of the shipment.

Because that is not a question.
Also, because there is no wildcard at the end. `shipment` must be the last word.

We do have answer types around time / date as well.

    ?:NUM:time *
    ?:NUM:date *
    ?:NUM:period * 

You will have to play with those to see how they compare and differ.

When you put in a tilde `~` this means to search for a concept (either user defined or from wordnet) and it is not a lemma word. You can think if this as meaning you want to expand the word into a series of similar words. There is no built in or user defined `~time`, but you can always create one.

`~yes` is a little special. Normalizer will convert many things to `~yes`
Have a look at https://github.com/silentrob/normalizer/blob/master/data/interjections.txt for more on that.

**Comment by dcsan** [comment]
thanks very much! this type of authoring info maybe new to many people who are using the engine that are coming from more of a web/conventional coding background, very helpful!
