### ISSUE TITLE
Images, html,css and javascript

### ISSUE THREAD

**Issue by airport-transfers** [silentrob/superscript#76]
Is it possible to show images, html and use javascript with superscript? If yes, is it possible to see an example?

**Comment by silentrob** [comment]
Can you expand on this a little. Describe what your trying to do and that might help.

SuperScript is a library that can be build into a webserver or chat client that serves html/css/js. 
And SuperScript replies return JSON, that can have other properties, like emoticons or images etc. I can show some examples if you elaborate on your use case.

**Comment by airport-transfers** [comment]
IMG Example 1:
+ Show me please photos of my car
- I have one photo of your car here is it <img ........... </img>

IMG Example 2:
+ Please show me the photo of the Ferrari F40
- Ok, done, here a gallery of photos of the Ferrari F40 car:
PHOTOGALLERY

CSS/HTML Example:
+ Show me please my personal data 
- <h5>Name:</h5> <h6>yourname</h6>
^ <h5>Surname:</h5><h6>yoursurname</h6>
^ <h5>Address:</h5> your address</h6>

JAVASCRIPT Example:
+ Which date is today?
- Today is <script>document.getElementById("demo").innerHTML = Date();</script>

**Comment by silentrob** [comment]
Awesome, thanks! 

Okay, example one is a bit loaded.. do you want to send TEXT or an IMG TAG or a PNG or the File contents of the image (Data URL)?
SuperScript has a concept of Out of bound data.. what that means is when you reply to something you get an JS Object back, and the ` - reply` is actually just a property on that object  `{ string:'...'}`

So lets say you want to add an image to the message. 

    + show * photos * car
    - I have one photo of your car here is it ^ addMessageProp(img, http://billeebrady.com/wp-content/uploads/2010/07/MyCar-028.jpg)

Here is the docs for that. http://superscriptjs.com/documentation/scripting#oob
Keep in mind, the client will need to do something with that data.

The other two examples can be done with plugins. Lets look at the third because I already have a plugin for that use-case already. 

https://github.com/silentrob/superscript/blob/master/plugins/time.js

    + (what|which) * date is today
    - Today is ^ getDate()

I think you should have enough info to figure out the other use case.
