### ISSUE TITLE
flags system, nostay seems no work

### ISSUE THREAD

**Issue by killix** [silentrob/superscript#91]
here main.ss
```
> topic presentation (presentation me)

    + hello my name is *
    - Nice to meet you <cap1>. ^save(name,<cap1>)

    + hello again
    - Hi ^get(name)
< topic

> topic topic_name (who knock)

    + where I can go
    - ^topicRedirect(rec_sys, __where_go__)

< topic

> topic:system,nostay rec_sys

    + __where_go__
    - What country are you thinking?
    - Where?

        # i don't know
        + ~emoignorance
        % *
        - {keep} case no know

        # doesn't matter
        + * (do|does) not matter
        % *
        - {keep} case not care

        + *~40
        % *
        - case one
        - case two
            + *
            - cool finish!
< topic
```
and the transcript
```
Hello 127.0.0.1:59203! Type /quit to disconnect.

You> where I can go

Bot> Where?
You> i don't know

Bot> case no know
You> where I can go

Bot> case one
You>
```

i think the pending topic is not reseted after reply, right? I can try to fix it but i need way where i go ;)

**Comment by killix** [comment]
hmm i think the issue is around ```- ^topicRedirect(rec_sys, __where_go__)```...

**Comment by silentrob** [comment]
I can take a look at this functionality today, I see I documented it, but there is no test coverage for it. 
I would imagine in processTags.js we would roll the current topic back one. (or something like that.)

**Comment by killix** [comment]
when i investigate, i found one issue in conversation parsing and parent's reply. Is not really related but i prepare a fix for that.

**Comment by silentrob** [comment]
Okay. Ive added the no-stay to the topic model. It was working back when superscript only checked one topic per cycle. 

I want to think this though a little more, and I welcome your feedback, as I think there is another bug.
So my thoughts are system topics are removed from the main TF-IDF flow and only available though ^respond(..) and ^topicRedirect(..)

If a match is found in the topic we leave, except if there is a conversation, it will check there, then go back the pending topics.

Let me illustrate this with an example.


    // random
    + test
    - ^respond(hidden)

    + no
    - end

    > topic:system hidden
    + this is a system topic
    - some reply

    + yes
    % some reply
    - this should work.

    + no
    -  wont work

    < topic


So 

    > test
    < some reply

    > yes
    < this should work

Because yes is in the conversation reply we continue with this. But all other gambits are still hidden.

BUT

    > test
    < some reply

    > no
    < end

In this case we bounce back to `random` and keep the default pending topics. (system is hidden) and no is not accessible.


Thoughts?

**Comment by silentrob** [comment]
If the system works as described, there should be no need for a no-stay flag as that is the default behaviour.

**Comment by silentrob** [comment]
Okay, this should now work. There was a bug in the conversation flow logic. We look at the previous convo, but when that is done we skip over the rest of the topic we were in. This change will now re-scan the existing current topic after searching the previous thread.

**Comment by killix** [comment]
:+1:  i will test it soon ;) thanks!
